### ISSUE TITLE
Aggregation is not updated 

### ISSUE THREAD

**Issue by KseniiaChumachenko** [KseniiaChumachenko/body-monitor#1]
Aggregation on Meal table is not updated after meal_items of particular meal changed. Replace FE calculation with Hasura computed field.

https://hasura.io/docs/1.0/graphql/manual/schema/computed-fields.html

**Comment by timeofneon** [comment]
Currently header of expansion panel is not refetched.

**Comment by KseniiaChumachenko** [comment]
Resolved with aggregations on db select + gql subscription.
